# filepath: .github/workflows/publish.yaml
name: Publish OSFM Package

on:
  push:
    branches:
      - osfm-py
    tags:
      - 'v*'

jobs:
  build-and-publish:
    if: github.ref == 'refs/heads/osfm-py'
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build --sdist --wheel .

      - name: Publish package to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*