# filepath: .github/workflows/publish.yaml
name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    branches:
      - osfm-py

jobs:
  build-and-publish:
    if: github.ref == 'refs/heads/osfm-py'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdm
          pdm install

      - name: Build package
        run: pdm build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}