# filepath: .github/workflows/publish.yaml
name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    branches:
      - osfm-py

jobs:
  build-and-publish:
    if: github.ref == 'refs/heads/osfm-py'
    runs-on: ubuntu-latest  # Keep ubuntu-latest for general checks

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Build on both Linux and Windows

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdm
          pdm install

      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          python -m pip install pdm
          pdm install

      - name: Build package
        run: pdm build

      - name: Install twine
        run: python -m pip install twine

      - name: Publish package to PyPI
        if: matrix.os == 'ubuntu-latest' # Only publish from one OS
        run: |
          python -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}